search()
install.packages("dplyr")
library("dplyr")
refine_original <- file.choose()
refine_csv <- read.csv(refine_original, header = TRUE, stringsAsFactors = FALSE)
head(refine_csv)
class(refine_csv)
unique(refine_csv$company)
refine_df <- tbl_df(refine_csv)
glimpse(refine_df)
unique(refine_df$company)
refine_df$company <- tolower(refine_df$company)
refine_df$company <- gsub("ph.*\\ps$", "philips", refine_df$company)
refine_df$company <- gsub("f.*\\ps$", "philips", refine_df$company)
refine_df$company <- gsub("ak.*$", "akzo", refine_df$company)
refine_df$company <- gsub("uni.*$", "unilever", refine_df$company)
head(refine_df)
install.packages("tidyr")
library("tidyr")
refine_df <- separate(refine_df, Product.code...number, c("product_code", "product_number"), sep = "-")
head(refine_df)
product_code <- c("p", "v", "x", "q")
product_category <- c("Smartphone", "TV", "Laptop", "Tablet")
categories <- cbind(product_code, product_category)
categories_df <- tbl_df(categories)
categories_df
refine_df <- left_join(categories_df, refine_df)
head(refine_df)
refine_df <- unite(refine_df, full_address, address, city, country, sep = ",")
head(refine_df)
refine_df$full_address[1]
refine_df <- mutate(refine_df, company_philips = ifelse(company == "philips",1,0))
refine_df <- mutate(refine_df, company_akzo = ifelse(company == "akzo",1,0))
refine_df <- mutate(refine_df, company_van_houten = ifelse(company == "van houten",1,0))
refine_df <- mutate(refine_df, company_unilever = ifelse(company == "unilever",1,0))
head(refine_df)
refine_df <- mutate(refine_df, product_smartphone = ifelse(product_category == "Smartphone",1,0))
refine_df <- mutate(refine_df, product_tv = ifelse(product_category == "TV",1,0))
refine_df <- mutate(refine_df, product_laptop = ifelse(product_category == "Laptop",1,0))
refine_df <- mutate(refine_df, product_Tablet = ifelse(product_category == "Tablet",1,0))
head(refine_df)
write.csv(refine_df, file = "refine_clean.csv")
